FROM node:22-alpine

WORKDIR /app

COPY izyPizy/frontend/package*.json ./
RUN npm ci

COPY izyPizy/frontend/ ./

RUN npm run build

FROM nginxinc/nginx-unprivileged:alpine

COPY --from=0 /app/dist /usr/share/nginx/html
COPY izyPizy/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]