/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{svelte,js,ts}'],
  theme: {
    extend: {
      colors: {
        dominant: 'rgb(var(--color-dominant-rgb) / <alpha-value>)',
        secondary: 'rgb(var(--color-secondary-rgb) / <alpha-value>)',
        accent: 'rgb(var(--color-accent-rgb) / <alpha-value>)',
        accentHover: 'rgb(var(--color-accent-hover-rgb) / <alpha-value>)',
        muted: 'rgb(var(--color-muted-rgb) / <alpha-value>)',
        surface: 'rgb(var(--color-surface-rgb) / <alpha-value>)',
        surfaceAlt: 'rgb(var(--color-surface-alt-rgb) / <alpha-value>)',
        ink: 'rgb(var(--color-border-rgb) / <alpha-value>)',
        success: 'rgb(var(--color-success-rgb) / <alpha-value>)',
        danger: 'rgb(var(--color-danger-rgb) / <alpha-value>)',
        mustard: '#F4A261',
        red: {
          50: '#FDF0EF',
          100: '#FADCDA',
          200: '#F5B9B5',
          300: '#EE8D86',
          400: '#E65A55',
          500: '#E63946',
          600: '#C22B38',
          700: '#9E1F2C',
          800: '#7C1823',
          900: '#5C121B',
        },
      },
      fontFamily: {
        display: ['"Archivo Black"', '"Arial Black"', 'system-ui', 'sans-serif'],
        body: ['"Space Grotesk"', 'system-ui', 'sans-serif'],
        mono: ['"IBM Plex Mono"', 'ui-monospace', 'monospace'],
      },
      boxShadow: {
        sm: '2px 2px 0 0 var(--color-border)',
        DEFAULT: '3px 3px 0 0 var(--color-border)',
        md: '4px 4px 0 0 var(--color-border)',
        lg: '5px 5px 0 0 var(--color-border)',
        xl: '6px 6px 0 0 var(--color-border)',
        '2xl': '8px 8px 0 0 var(--color-border)',
        inner: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
        none: 'none',
      },
      borderRadius: {
        none: '0',
        sm: '2px',
        DEFAULT: '4px',
        md: '5px',
        lg: '6px',
        xl: '8px',
        '2xl': '10px',
        '3xl': '14px',
        full: '9999px',
      },
      borderWidth: {
        DEFAULT: '2px',
        0: '0',
        2: '3px',
        4: '4px',
        8: '8px',
      },
    },
  },
  plugins: [],
}
